services:
  pgsql:
    image: postgres:16
    container_name: postgres16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: userexplorer
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data:
